// ;[
//   // every 11th element  document.querySelectorAll('td')[1].lastElementChild.childNodes[0]; - name
//   // document.querySelectorAll('td')[10].lastElementChild.childNodes[0].src; - img
//   // obj with a name prop and it will contain first thing and img obj for second thing

//   '202',
//   "'93 Camaro",
//   'Purple',
//   'Red, Yellow "Camaro" on sides',
//   'Black / Plastic',
//   'Black tint',
//   'Gray',
//   'UH',
//   '3021',
//   '',
//   '',
//   '208',
//   'Avus Quattro',
//   'Met. Silver',
//   'Silver and Black on roof',
//   'Black / Plastic',
//   'Clear',
//   'Red',
//   'UH',
//   '5250',
//   '',
//   '',
//   '210',
//   'Dodge Viper RT/10',
//   'Red',
//   'No Tampos',
//   'Black',
//   'Clear',
//   'Black',
//   'UH',
//   '5265',
//   '',
//   '',
//   '203',
//   'Jaguar XJ220',
//   'Metallic Silver',
//   'No Tampo',
//   'Black / Plastic',
//   'Clear',
//   'Black',
//   'UH',
//   '3026',
//   '',
//   '',
//   '209',
//   'Lexus SC400',
//   'Metalflake Black',
//   'no tampo',
//   'Black / Plastic',
//   'Clear',
//   'White',
//   'BW',
//   '5263',
//   '',
//   '',
//   '204',
//   'Oscar Mayer Wienermobile',
//   'Red, Yellow and Tan',
//   'Whit & Red "Oscar Mayer" Logo',
//   'Black / Metal',
//   'Black tint',
//   'unseen',
//   'BW Black',
//   '3029',
//   '',
//   '',
//   '206',
//   'Pipe Jammer',
//   'Yellow',
//   'no tampo',
//   'Black Metal',
//   'N/A',
//   'Chrome',
//   'UH',
//   '3036',
//   '',
//   '',
//   '212',
//   'Silhouette II',
//   'Met. Purple w/Chrome Engine',
//   'no tampo',
//   'Chrome Plastic',
//   'Clear',
//   'White',
//   'UH',
//   '5267',
//   '',
//   '',
//   '205',
//   'Treadator',
//   'Red & Chrome',
//   'no tampo',
//   'Black / Plastic',
//   'Chrome',
//   'N/A',
//   'Black track with tiny rollers',
//   '3035',
//   '',
//   '',
//   '211',
//   'Twin Mill II',
//   'Bright Yellow-Green',
//   'no tampo',
//   'Chrome / Plastic',
//   'Black tint',
//   'none',
//   'UH',
//   '5266',
//   '',
//   '',
//   '149',
//   'BMW 850i',
//   'Blue',
//   'Pink, Blue, Yellow, White, markings',
//   'Blue Plastic',
//   'Clear',
//   'Tan',
//   'HOC',
//   '5667',
//   '',
//   '',
//   '149',
//   'BMW 850i',
//   'Blue',
//   'Pink, Blue, Yellow, White, markings',
//   'Blue Plastic',
//   'Clear',
//   'Tan',
//   'LIW',
//   '5667',
//   '',
//   '',
//   '197',
//   'Corvette Split Window',
//   'Blue',
//   'Yellow, Red and Purple graphics',
//   'Chrome Plastic',
//   'Clear',
//   'Red',
//   'WW',
//   '3092',
//   "Originally named Spit Window '63",
//   '',
//   '197',
//   'Gleamer Patrol',
//   'Textured Chrome',
//   'no tampo',
//   'Unpainted / Metal',
//   'Blue tint',
//   'Black',
//   'BW',
//   '1691',
//   'Originally named Highway Patrol',
//   '',
//   '200',
//   'Corvette Convertible',
//   'White',
//   'Black, Red, Yellow "CORVETTE" on hood and sides',
//   'Black / Plastic',
//   'clear',
//   'Red',
//   'UH',
//   '2898',
//   '',
//   '',
//   '224',
//   'Zombot',
//   'Blue Chrome.Pink Gun',
//   '',
//   'Unpainted / Metal',
//   '',
//   '',
//   'UH',
//   '3852',
//   '',
//   '',
//   '228',
//   'Zender Fact 4',
//   'Blue metallic',
//   'Zender Fact 4',
//   'Black plastic',
//   'Dark tinted',
//   'Black',
//   'UH',
//   '4407',
//   '',
//   '',
//   '232',
//   'Lamborghini Countach',
//   'Red',
//   'White, Black "Countach"',
//   'Red / Metal',
//   'Black tint',
//   'Black',
//   'UH',
//   '4384',
//   '',
//   '',
//   '214',
//   'Swingfire',
//   'Metalflake Dark Blue',
//   'Yellow & White deco on hood',
//   'Unpainted / Metal',
//   'Clear',
//   'White',
//   'White Wall BW',
//   '4312',
//   '',
//   '',
//   '215',
//   'Auburn 852',
//   'Red',
//   'None',
//   'Unpainted / Metal',
//   'Clear',
//   'Black',
//   'White Wall BW',
//   '4314',
//   '',
//   '',
//   '232',
//   'Lamborghini Countach',
//   'White',
//   'None',
//   'White / Metal',
//   'Tinted (Black)',
//   'Red',
//   '5DOT',
//   '4384',
//   '',
//   '',
//   'Baja Breaker',
//   'Maroon with fading Yellow front',
//   'Black, Yellow, Red, White mouth with fangs',
//   'unpainted metal',
//   'Clear',
//   'Red',
//   'BW',
//   '3490',
//   'Open Wide',
//   '',
//   'Rapid Transit',
//   'White',
//   'Brown, Orange, Green covered in words',
//   'Unpainted Metal',
//   'Clear',
//   'Unpainted Metal',
//   'BW',
//   '3502',
//   'Bus Boys',
//   '',
//   'Rapid Transit',
//   'Yellow',
//   'Brown, Orange, Green covered in words',
//   'Unpainted Metal',
//   'Clear',
//   'Unpainted Metal',
//   'BW',
//   '3502',
//   'Bus Boys',
//   '',
//   'Porsche 959',
//   'Yellow & Light Green',
//   'Red, Black , Blue Eyes',
//   'unpainted metal',
//   'Clear',
//   'Grey',
//   'BW',
//   '3493',
//   'Eye-Gor',
//   '',
//   'Race Bait 308',
//   'Blue',
//   'White, Red, Yellow, Hot Wheels Logos',
//   'Black / Metal',
//   'Grey tint',
//   'Black',
//   'BW',
//   '3494',
//   '"Hot Wheels"',
//   '',
//   'BMW 323',
//   'Metallic Pink',
//   'Black & White Skulls, Green & Black Snakes',
//   'Black / Plastic',
//   'Clear',
//   'Tan',
//   'BW',
//   '3492',
//   'Skull Rider',
//   '',
//   'Talbot Lago',
//   'White',
//   'Black and Red Spiders',
//   'Unpainted / Metal',
//   'Red tint',
//   'Chrome',
//   'WW',
//   '3479',
//   'Spiderider',
//   '',
//   'BMW M1',
//   'Met. Blue',
//   'Purple, Blue and Red dogs',
//   'Black / Metal',
//   'Grey tint',
//   'Black',
//   'BW',
//   '',
//   'Street Dog',
//   '',
//   'Sting Rod',
//   'Met. Silver',
//   'Yellow, Black, Green, Red markings',
//   'Black / Metal',
//   'Met. Blue',
//   'Black',
//   'CTS Black',
//   '3527',
//   'Ammo',
//   '',
//   'Science Friction',
//   'Blue',
//   'Blue, Pink, Light Green, lightning bolts',
//   'Metal',
//   'Chrome',
//   'unseen',
//   'BW',
//   '',
//   'Lightning Storm',
//   '',
//   'Speed Blaster',
//   'Green with fading Yellow rear',
//   'Yellow, Green, Red, dragon',
//   'Green / Plastic',
//   'Chrome',
//   'unseen',
//   'BW',
//   '',
//   'Dragon Wagon',
//   '',
//   '',
//   'Red',
//   'Yellow, Black, White, skull, treasure map, sword',
//   'Black / Plastic',
//   'Chrome',
//   'unseen',
//   'BW',
//   '',
//   'Road Pirate',
//   '',
//   'Monster Vette',
//   'Yellow',
//   'Black, Orange, White, tigers & stripes',
//   'unpainted metal',
//   'Grey tint',
//   'Grey tint',
//   'CTS',
//   '3716',
//   '"Street Beast"',
//   '',
//   '10566',
//   '1/9',
//   '1993 Demolition Man Series',
//   'Oldsmobile Aurora',
//   '',
//   '11082',
//   '2/9',
//   '1993 Demolition Man Series',
//   'Olds 442 W-30',
//   '',
//   '11083',
//   '3/9',
//   '1993 Demolition Man Series',
//   'GM Ultralite',
//   '',
//   '11084',
//   '4/9',
//   '1993 Demolition Man Series',
//   'GM Lean Machine',
//   '',
//   '11085',
//   '5/9',
//   '1993 Demolition Man Series',
//   'Corvette Stingray III',
//   '',
//   '11087',
//   '6/9',
//   '1993 Demolition Man Series',
//   'Pontiac Salsa',
//   '',
//   '11088',
//   '7/9',
//   '1993 Demolition Man Series',
//   'Pontiac Banshee',
//   '',
//   '11089',
//   '8/9',
//   '1993 Demolition Man Series',
//   'Buick Wildcat',
//   '',
//   '11090',
//   '9/9',
//   '1993 Demolition Man Series',
//   'Chevrolet ACC Camaro',
//   '',
//   '5700',
//   'Red Baron',
//   'Metalflake Bright Red',
//   'Unpainted / metal',
//   '',
//   'Black',
//   'Red Line',
//   'china',
//   '',
//   '',
//   '5707',
//   'Paddy Wagon',
//   'Metallic Brown / Matt Black',
//   'Unpainted / metal',
//   'Blue tinted',
//   'Black',
//   'Red Line',
//   'china',
//   '',
//   '',
//   '5708',
//   "Splittin' Image",
//   'Metallic Brown',
//   'Unpainted / metal',
//   'Grooved and blue tinted',
//   'Tan',
//   'Red Line',
//   'china',
//   '',
//   '',
//   '5709',
//   'Twin Mill',
//   'Metallic Pink',
//   'Metal / Metallic Pink',
//   'Clear',
//   'white',
//   'Red Line',
//   'china',
//   '',
//   '',
//   '5714',
//   'Beatnik Bandit',
//   'Metallic Lime Green',
//   'Unpainted / metal',
//   'Blue tinted',
//   'white',
//   'Red Line',
//   'china',
//   '',
//   '',
//   '5715',
//   'Silhouette',
//   '',
//   'Body colored metal',
//   'Purple tinted',
//   '',
//   'Red Line',
//   'china',
//   '',
//   '',
//   '5730',
//   'The Demon',
//   'Metallic Turquoise',
//   'Unpainted / metal',
//   'Blue tinted / clear',
//   'Black',
//   'Red Line',
//   'china',
//   '',
//   '',
//   '5743',
//   'Classic Nomad',
//   'Metallic Violet',
//   'Unpainted / metal',
//   'Clear',
//   'white',
//   'Red Line',
//   'china',
//   'Hood opens',
//   '',
//   'Yearly Lists of Basic Line and Other collections',
//   'By Year:\n\n\n1968 • 1969 • 1970 • 1971 • 1972 • 1973 • 1974 • 1975 • 1976 • 1977 • 1978 • 1979 • 1980 • 1981 • 1982 • 1983 • 1984 • 1985 • 1986 • 1987 • 1988 • 1989 • 1990 • 1991 • 1992 • 1993 • 1994 • 1995 • 1996 • 1997 • 1998 • 1999 • 2000 • 2001 • 2002 • 2003 • 2004 • 2005 • 2006 • 2007 • 2008 • 2009 • 2010 • 2011 • 2012 • 2013 • 2014 • 2015 • 2016 • 2017 • 2018 • 2019 • 2020 • 2021\n\nBy Collection:\nFlying Colors • Super Chromes (original) • Collector Numbers 1 - 1121 • The Hot Ones • Real Riders • Speed Machines • Classics (original) • Ultra Hots (original) • 100% • Pro Racing • Hot Wheels Racing • Hall of Fame • Auto Affinity • Classics • Flying Customs • Super Chromes (reboot) • Garage • Dragstrip Demons • Speed Machines (reboot) • Delivery • Vintage Racing • Nostalgic Brands • Boulevard • Ultra Hots (reboot) • Cool Classics • Heritage • Retro Style\nEntertainment • Pop Culture • Car Culture • Car Culture: Team Transport • Boulevard (reboot) •\nHolidays • Color Changers • Color Shifters • Hot Wheels Monster Trucks • Monster Jam • Character Cars • Mario Kart\nFast & Furious Series • Fast & Furious Premium\nHW Anniversary Series • HWC.com • Red Line Club'
// ]
